import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavigationBar from "./../components/NavigationBar";
import Welcome from "./../components/Welcome";

export default function Home() {
  return (
    <>
      <Head>
        <title>Japa101</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Welcome />
      </main>
    </>
  );
}
